apiVersion: v1
kind: Service
metadata:
  name: calculator-microservice-service
spec:
  selector:
    app: calculator-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
