name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/fdpdevops:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/fdpdevops:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/fdpdevops:${{ github.sha }}

    - name: Run tests
      run: docker run ${{ secrets.DOCKER_USERNAME }}/fdpdevops:${{ github.sha }} npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Minikube
      uses: manusa/actions-minkube@v2.4.0
      with:
        minikube version: 'v1.23.0'
        kubernetes version: 'v1.21.2'

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
